{% set name = "veloxchem" %}
{% set version = "1.0rc1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../../vlx-conda-build
  #sha256: 1a8a667f4c81601daa43e1339d91f1594fb5525fe0869dce5e187c49430a769c

build:
  number: 0
  binary_relocation: true
  entry_points:
    - vlx=veloxchem.main:main
  ignore_run_exports:
    - mpi4py
    - python
  run_exports:
    - {{ pin_subpackage('veloxchem', max_pin='x.x') }}

requirements:
  build:
    - cmake >=3.17
    - {{ compiler('cxx') }}
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
    - ninja
  host:
    - pybind11 >=2.6
    - python {{ python }}
    - libblas * *mkl
    - mkl-devel
    - {{ mpi }}
    - mpi4py
    - numpy >=1.13.0
    - xtb                          # [not win]
    - gtest
  run:
    - cppe                         # [not win]
    - psutil
    - geometric
    - loprop
    - {{ mpi }}
    - mpi4py
    - h5py
    - {{ pin_compatible('python', max_pin='x.x') }}

test:
  requires:
    - pytest
  imports:
    - veloxchem
  commands:
    # Verify existence and execution
    - test -d $SP_DIR/veloxchem  # [not win]
    - ls -l $SP_DIR/veloxchem    # [not win]
    - test -f $PREFIX/bin/vlx    # [not win]
    - $PREFIX/bin/vlx --version  # [not win]
    - $PREFIX/bin/vlx --help     # [not win]
    - if not exist %SP_DIR%\\veloxchem exit 1  # [win]
    - dir %SP_DIR%\\veloxchem                  # [win]
    - if not exist %PREFIX%\\bin\\vlx exit 1   # [win]
    - %PREFIX%\\bin\\vlx --version             # [win]
    - %PREFIX%\\bin\\vlx --help                # [win]
    # Verify Python extension library
    - export PYLIB_EXT=`$PYTHON -c 'from numpy import distutils; print(distutils.misc_util.get_shared_lib_extension(is_python_ext=True))'`  # [not win]
    - FOR /F "tokens=* USEBACKQ" %g IN (`%PYTHON% -c 'from numpy import distutils; print(distutils.misc_util.get_shared_lib_extension(is_python_ext=True))'`) DO (SET "PYLIB_EXT=%g")  # [win]
    - test -f $SP_DIR/veloxchem/veloxchemlib$PYLIB_EXT                 # [not win]
    - if not exist %SP_DIR\\veloxchem\\veloxchemlib%PYLIB_EXT% exit 1  # [win]
    # Inspect linkage
    - ldd -v $SP_DIR/veloxchem/veloxchemlib$PYLIB_EXT    # [linux]
    - otool -L $SP_DIR/veloxchem/veloxchemlib$PYLIB_EXT  # [osx]
    # run integration tests
    - export OMP_NUM_THREADS=$CPU_COUNT                     # [not win]
    - mpirun -n 1 $PYTHON -m pytest --pyargs veloxchem      # [not win]
    - export MPI_NUM_PROCS=2                                # [not win]
    - export OMP_NUM_THREADS=$(($CPU_COUNT/$MPI_NUM_PROCS)) # [not win]
    - mpirun -n $MPI_NUM_PROCS $PYTHON -m pytest --pyargs veloxchem -m solvers  # [not win]
    - set OMP_NUM_THREADS=%CPU_COUNT%                      # [win]
    - mpiexec -n 1 $PYTHON -m pytest --pyargs veloxchem -k "not loprop"  # [win]
    - set MPI_NUM_PROCS=2                                  # [win]
    - set /A OMP_NUM_THREADS="%CPU_COUNT%/%MPI_NUM_PROCS%" # [win]
    - mpiexec -n %MPI_NUM_PROCS% %PYTHON% -m pytest --pyargs veloxchem -m solvers -k "not loprop"  # [win]

outputs:
  - name: veloxchem
    files:
      - {{ SP_DIR }}/veloxchem  # [not win]
      - {{ SP_DIR}}\\veloxchem  # [win]

about:
  home: https://veloxchem.org
  dev_url: https://gitlab.com/veloxchem/veloxchem
  doc_url: https://veloxchem.org/manual
  doc_source_url: https://gitlab.com/veloxchem/veloxchem/-/blob/master/docs/index.rst
  license: LGPL-3.0-or-later
  license_url: https://opensource.org/licenses/LGPL-3.0
  license_file: LICENSE
  license_family: LGPL
  summary: A Python-based, open source quantum chemistry program package

extra:
  recipe-maintainers:
    - robertodr
