name: Deploy Python packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipes: [daltools, fortran-binary, loprop]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: deploy
        environment-file: .github/deploy.yml
        channel-priority: true

    - name: ${{ matrix.recipes }}
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda config --set anaconda_upload yes
        cd $GITHUB_WORKSPACE/conda-recipes
        conda build ${{ matrix.recipes }} -c conda-forge --verify --user robertodr --token $ANACONDA_TOKEN
