name: Deploy C++ packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        recipes: [cppe]

    steps:
      - uses: actions/checkout@v2

      - name: Install macOS SDK
        if: contains( matrix.os, 'macos')
        working-directory: /Users/runner
        run: |
          curl -fsSL https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.9.sdk.tar.xz > ~/MacOSX10.9.sdk.tar.xz
          tar -xzf ~/MacOSX10.9.sdk.tar.xz
          rm ~/MacOSX10.9.sdk.tar.xz

      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0  # Increase this value to reset cache if .github/deploy.yml has not changed
        with:
          path: ~/conda_pkgs_dir
          key:
            cxx-deps-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/deploy.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: deploy
          environment-file: .github/deploy.yml
          channel-priority: true
          python-version: 3.8
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

      - name: Build and upload ${{ matrix.recipes }}
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/conda-recipes
          conda build ${{ matrix.recipes }} -c conda-forge --user robertodr --token $ANACONDA_TOKEN --label main --verify
