name: Deploy Python packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipes: [daltools, fortran-binary, loprop]

    steps:
    - uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0  # Increase this value to reset cache if .github/deploy.yml has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          py-deps-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/deploy.yml') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: deploy
        environment-file: .github/deploy.yml
        channel-priority: true
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

    - name: Build and upload ${{ matrix.recipes }}
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda config --set anaconda_upload yes
        cd $GITHUB_WORKSPACE/conda-recipes
        conda build ${{ matrix.recipes }} -c conda-forge --verify --user robertodr --token $ANACONDA_TOKEN --label main
